version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: meu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: new0147      
      MYSQL_DATABASE: dbpython            
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: minha-api
    ports:
      - "5000:5000"
    depends_on:
      - mysql

volumes:
  mysql_data:
